version: "3.7"
services:
    superspider-mongo:
        image: mongo
        container_name: superspider-mongo
        restart: unless-stopped
        volumes:
            - mongodata:/data/db
        environment:
            NODE_ENV: production
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
    superspider-predb:
        image: acedroidx/superspider-predb:master
        container_name: superspider-predb
        restart: unless-stopped
        depends_on:
            - superspider-mongo
        environment:
            NODE_ENV: production
            MONGODB_PASS: admin
            MONGODB_IP: superspider-mongo
            room_id: 437817,21452505
            fullmsg_id: 437817,21452505
    superspider-mdb:
        image: acedroidx/superspider-mdb:master
        container_name: superspider-mdb
        restart: unless-stopped
        depends_on:
            - superspider-mongo
        environment:
            NODE_ENV: production
            MONGODB_PASS: admin
            MONGODB_IP: superspider-mongo
            room_id: 437817,21452505
    superspider-mcore:
        image: acedroidx/superspider-mcore:master
        container_name: superspider-mcore
        restart: unless-stopped
        depends_on:
            - superspider-mongo
            - superspider-mdb
        environment:
            NODE_ENV: production
            MONGODB_PASS: admin
            MONGODB_IP: superspider-mongo
        ports:
            - "2162:2162"
    superspider-showcase:
        image: hikariri123/superspider-showcase:master
        container_name: superspider-showcase
        environment:
            BASE_API_URL: http://192.168.6.60:2162
            room_id: 437817,21452505
        ports:
            - "2164:2164"

volumes:
    mongodata:
        name: "superspider-mongodata"
